# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file RobotControlnterface/pom.xml

    - name: Run Tests
      run: mvn -B test --file RobotControlnterface/pom.xml

    - name: Update README with Test Status
      if: always()
      run: |
        # Set the TEST_STATUS and TEST_COLOR variables
        TEST_STATUS=$(if [ "success" == "success" ]; then echo "passing"; else echo "failing"; fi)
        TEST_COLOR=$(if [ "success" == "success" ]; then echo "brightgreen"; else echo "red"; fi)
        echo "TEST_STATUS: ${TEST_STATUS}"
        echo "TEST_COLOR: ${TEST_COLOR}"
        
        # Debugging: Print the existing badge line
        echo "Existing badge line (before update):"
        grep 'Test Status' README.md || echo "Badge not found in README.md"
        
        # Add the badge if it doesn't exist
        if ! grep -q 'Test Status' README.md; then
          echo "Badge not found in README.md adding new one"
          echo -e "![Test Status](https://img.shields.io/badge/tests-${TEST_STATUS}-${TEST_COLOR})\n$(cat README.md)" > README.md
        else
          # Update the README.md file
          echo "Badge found in README.md updating it"
          sed -i 's|![Test Status](https://img.shields.io/badge/tests-[^)]*)|![Test Status](https://img.shields.io/badge/tests-'${TEST_STATUS}'-'${TEST_COLOR}')|' README.md
        fi
        
        # Debugging: Print the updated badge line
        echo "Updated badge line (after update):"
        grep 'Test Status' README.md || echo "Badge not updated in README.md"
        
        # Check if there are changes in README.md
        if ! git diff --quiet README.md; then
          echo "Changes detected in README.md"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Update test status badge"
          git push
        else
          echo "No changes detected in README.md"
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
